/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kelinlang_stream_media_lib_jni_MediaPlayerJni */

#ifndef _Included_com_kelinlang_stream_media_lib_jni_MediaPlayerJni
#define _Included_com_kelinlang_stream_media_lib_jni_MediaPlayerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_create
  (JNIEnv *env, jobject object);

/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    setVideoSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_setVideoSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    setParam
 * Signature: (Lcom/kelinlang/stream/media/lib/jni/PlayerParam;)V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_setParam
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_init
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_release
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_start
  (JNIEnv *, jobject);

/*
 * Class:     com_kelinlang_stream_media_lib_jni_MediaPlayerJni
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_MediaPlayerJni_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}



#endif
#endif
