/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kelinlang_stream_media_lib_jni_StreamMediaJni */

#ifndef _Included_com_kelinlang_stream_media_lib_jni_StreamMediaJni
#define _Included_com_kelinlang_stream_media_lib_jni_StreamMediaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kelinlang_stream_media_lib_jni_StreamMediaJni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelinlang_stream_media_lib_jni_StreamMediaJni_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
